version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=my_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5431:5431'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  pgadmin: 
   image: dpage/pgadmin4
   environment: 
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
   ports:
     - "5050:80"